version: 0.2

phases:
  build:
    commands:
      - mkdir build-output
      - cp -R ssg/quickstart/public/ build-output
      - shopt -s extglob && rm -r !(build-output)
  post_build:
    commands:
      - mv build-output/**/* ./
      - mv build-output/* ./
      - rm -R build-output
artifacts:
  files:
    - '**/*'
