version: 0.2

phases:
  build:
    commands:
      - mkdir build-output
      - cp -R ssg/quickstart/public/ build-output
artifacts:
  files:
    - 'build-output/**/*'
  base-directory: build-output
  