version: 0.2

phases:
  build:
    commands:
      - mkdir build-output
      - cp -R ssg/quickstart/public/ build-output
  post_build:
    commands:
      - mv build-output/**/* ./
      - mv build-output/* ./
      - rm -R build-output *.yml LICENSE README* .git*
  #     - unzip public.zip -d public
artifacts:
  # type: zip
  files:
    - '**/*'
  # discard-paths: yes
  # base-directory: 'build-output'