version: 0.2

phases:
  build:
    commands:
      - ls
      # - mkdir build-output
      # - cp -R ssg/quickstart/public/ build-output
artifacts:
  files:
    - ssg/quickstart/public/**/*
cache:
  paths:
    - ./