version: 0.2

phases:
  build:
    commands:
      - ls

artifacts:
  files:
    - */public/**/*
  discard-paths: yes
  # files:
  #   - sg/quickstart/public/css/*
  # discard-paths: yes
  # base-directory: css
# artifactIdentifier3:
#   files:
#     - sg/quickstart/public/fonts/**/*
#   discard-paths: yes
#   base-directory: fonts
  # files:
  #   - sg/quickstart/public/images/*
  # discard-paths: yes
  # base-directory: images
  # files:
  #   - sg/quickstart/public/js/*
  # discard-paths: yes
  # base-directory: js
  # files:
  #   - sg/quickstart/public/tags/*
  # discard-paths: yes
  # base-directory: tags
