version: 0.2

phases:
  build:
    commands:
      - aws s3 sync --delete . s3://dem.tools-test-bucket
      - mkdir build-output
      - find . -type d -name public -exec cp -R {} build-output \;
      - find . -mindepth 1 -name build-output -prune -o -exec rm -rf {} +
  post_build:
    commands:
      - mv build-output/**/* ./
      - mv build-output/* ./
      - rm -R build-output
artifacts:
  files:
    - '**/*'
  name: $(AWS_REGION)-$(date +%Y-%m-%d) 
