# Page settings
baseURL = "http://dem.tools/"
languageCode = "en-us"
title = "2018 Year in Review | NDI DemTools"
theme = "elate"

[params]
  
  # custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Noble Ackerson"
  description = "DemTools | Cultivating Democracy"
  email = "nackerson@ndi.org"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = "AIzaSyBYFJ3tnlr9X5D_xeot0JJp30XnAwht3E4"

  # Google Tag Manager Container ID
  gtagmanagerID = "GTM-5NL7SGB"

  # Navigation
  [params.navigation]
    brand = "DemTools by NDI"
    home = "Home"
    services = "2019 Initiatives"
    counters = "2018 Stats"    
    testimonials = "Testimonials"
    tools = "Products and Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "https://datastudio.google.com/embed/reporting/1fvg5BejGgk1o1-lLgVHDXGJJodYmVyfH/page/FW7"
      name = "Data Dashboards"
      weight = 10
  
  # Hero section
  [params.hero]
    title = "2018 Year in Review"
    subtitle = 'A Year of Human Centered Design at NDI: what we learned by letting user feedback shape the solutions we build for you.'
    # TODO wire-up CTA button
    url = "https://www.demworks.org/citizen-centered-designing-technology-solutions-democracy-ndi"
    # cta = 'More on Human Centered Design'
 
  # Intro section
  # Available icons: http://simplelineicons.com/

  [params.intro]

  [[params.intro.item]]
    title = "Web Applications"
    description = "Helping you reduce the time to deliver web solutions so you can focus on amplifying your great work."
    url = "#"
    button = "Get In Touch"
    icon = "icon-globe"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Data Visualization"
    description = "Helping your stakeholders understand by interactive visual analysis and see the impact of their contributions."
    url = "#"
    button = "Learn More"
    icon = "icon-graph"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Distance Learning"
    description = "Helping empower citizens with self-paced knowledge material and fun interactive educational content."
    url = "http://techcivica.ndi.org"
    button = "Sign-up on TechCivica"
    icon = "icon-badge"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=frJ3swCd7Mk"

 # Counters section
  [params.counters]
    enable = true
    map = true
    title = "2018, by the numbers"
    subtitle = "Apollo Election Software"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Websites and applications delivered"
      icon = "icon-globe"
      from = 0
      to = 18
      interval = 50
      speed = 1000

    [[params.counters.item]]
      description = "Ideas & Feedback requests received"
      icon = "icon-bulb"
      from = 0
      to = 528
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Participants completed a TechCivica module"
      icon = "icon-graduation"
      from = 0
      to = 50
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "% monthly active users of DemGames"
      icon = "icon-trophy"
      from = 0
      to = 72
      interval = 50
      speed = 5000
      
    [[params.counters.row]]
      title = "Apollo deployments"

  # Services section
  [params.services]
    enable = true
    title = "Ahead for 2019"
    description = "Looking ahead this is what to expect from the technology team."

    [[params.services.item]]
      title = "Continued data privacy focus"
      description = "We will continue to improve how we handle the personal and sensitive information of our beneficiaries."
      icon = "icon-lock"

    [[params.services.item]]
      title = "A “One CRM” Initiative"
      description = "A contact relationship system for NDI staff to unifying our contact management and outreach initiatives."
      icon = "icon-people"
    [[params.services.item]]
      title = "Reducing the time to deliver websites"
      description = "You spoke and we heard! NDI Tech will be rolling out a new system to reduce the time and cost of deploying websites."
      icon = "icon-cloud-upload"

      [[params.services.item]]
      title = "Launch of new Software Feedback and Ideas Portal"
      description = "<strong>feedback.demcloud.org</strong> is a place for you to start capturing actionable feedback in a central place."      
      icon = "icon-layers"


  # Tools section
  [params.tools]
    enable = true
    title = "Tools"
    description = "The Democracy Toolkit (DemTools) is designed to help empower civil society organizations, political parties and legislatures around the world by applying technology solutions to common challenges."

    [[params.tools.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "CiviCRM"
      subtitle = "Contact management for constituent engagement, political organizing, and civic action."

    [[params.tools.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Apollo"
      subtitle = "Robust data collection and analysis to document causes, political processes, and outreach."

    [[params.tools.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "DemGames"
      subtitle = "Gamified learning platform to provide interactive, fun, and additive educational experiences at scale."

    [[params.tools.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Fix My Community"
      subtitle = "Information collection for CSOs and enables local and national governments to engage directly with citizen’s concerns and highlight good governance."

    [[params.tools.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Digital Security"
      subtitle = "Our consultants conduct in-person or remote security training from part-day awareness raising to week-long cybersecurity boot camps around the world."

    [[params.tools.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Human Centered Design"
      subtitle = "Creative problem solving approach that uses empathy and an iterative, explorative process to understand user needs and identify solutions to complex or poorly defined problems."
   

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    

  
  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Contact section
  [params.contact]
    enable = false
    map = false
    form = true
    title = "Get in touch"
    description = "Something witty to say in place of a template language"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "455 Massachusettes Avenue, <br> Washington D.C."],
        ["icon-phone", "(202) 123-4567"],
        ["icon-envelope", "info@ndi.org"],
        ["icon-globe", '<a href="https://www.ndi.org/" target="_blank">ndi.org</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; NDItech. All Rights Reserved. <br>Hugo port by: <a href="https://github.com/saey55" rel="noreferrer" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
